#!/bin/sh
set -eu

DMZ_SUBNET="${DMZ_SUBNET:-10.10.10.0/24}"
DMZ_ROUTE_NETWORK="${DMZ_ROUTE_NETWORK:-10.10.10.0}"
DMZ_ROUTE_NETMASK="${DMZ_ROUTE_NETMASK:-255.255.255.0}"
DMZ_ALLOWED_PORT="${DMZ_ALLOWED_PORT:-8080}"
RADIUS_ENABLED="${RADIUS_ENABLED:-false}"
OPENVPN_CONFIG=/etc/openvpn/openvpn.conf

append_config() {
    LINE="$1"
    grep -qF "$LINE" "$OPENVPN_CONFIG" || echo "$LINE" >> "$OPENVPN_CONFIG"
}

# Remove the unused route generated by the base image and push the real DMZ
# route to VPN clients. grep makes this idempotent across container restarts.
sed -i '/^route 192\.168\.254\.0 255\.255\.255\.0$/d' "$OPENVPN_CONFIG"
if ! grep -qF "push \"route ${DMZ_ROUTE_NETWORK} ${DMZ_ROUTE_NETMASK}\"" "$OPENVPN_CONFIG"; then
    echo "push \"route ${DMZ_ROUTE_NETWORK} ${DMZ_ROUTE_NETMASK}\"" >> "$OPENVPN_CONFIG"
fi

mkdir -p /run/openvpn-roles /var/log/shared
touch /var/log/shared/openvpn.log /var/log/shared/openvpn-radius.log

append_config "log-append /var/log/shared/openvpn.log"
append_config "verb 3"

# Remove previously managed authentication hooks before selecting the current
# mode. This keeps the shared vpn_data volume safe when switching between the
# standalone lab and the full RADIUS-enabled Compose stack.
sed -i \
    -e '/^auth-user-pass-verify \/usr\/local\/bin\/radius-auth.py via-file$/d' \
    -e '/^client-connect \/usr\/local\/bin\/apply-client-policy.sh$/d' \
    -e '/^client-disconnect \/usr\/local\/bin\/remove-client-policy.sh$/d' \
    -e '/^script-security 3$/d' \
    "$OPENVPN_CONFIG"

iptables -N VPN_ROLE_POLICY 2>/dev/null || iptables -F VPN_ROLE_POLICY
if [ "$RADIUS_ENABLED" = "true" ]; then
    # Policy scripts modify iptables, so the OpenVPN process remains root in
    # this isolated lab container.
    sed -i '/^user /d; /^group /d' "$OPENVPN_CONFIG"
    append_config "script-security 3"
    append_config "auth-user-pass-verify /usr/local/bin/radius-auth.py via-file"
    append_config "client-connect /usr/local/bin/apply-client-policy.sh"
    append_config "client-disconnect /usr/local/bin/remove-client-policy.sh"
    iptables -A VPN_ROLE_POLICY -j DROP
else
    iptables -A VPN_ROLE_POLICY -d "$DMZ_SUBNET" -p tcp --dport "$DMZ_ALLOWED_PORT" -j ACCEPT
    iptables -A VPN_ROLE_POLICY -j DROP
fi

iptables -C FORWARD -o tun0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT 2>/dev/null \
    || iptables -I FORWARD 1 -o tun0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -C FORWARD -i tun0 -j VPN_ROLE_POLICY 2>/dev/null \
    || iptables -I FORWARD 2 -i tun0 -j VPN_ROLE_POLICY

ovpn_run &
OPENVPN_PID=$!
trap 'kill "$OPENVPN_PID" 2>/dev/null || true; wait "$OPENVPN_PID" 2>/dev/null || true' INT TERM

i=0
while [ ! -d /sys/class/net/tun0 ] && [ "$i" -lt 30 ]; do
    sleep 1
    i=$((i + 1))
done

if [ ! -d /sys/class/net/tun0 ]; then
    echo "tun0 olusmadi; segmentasyon kurallari uygulanamadi." >&2
    kill "$OPENVPN_PID" 2>/dev/null || true
    wait "$OPENVPN_PID" 2>/dev/null || true
    exit 1
fi

echo "VPN segmentasyonu aktif. RADIUS_ENABLED=${RADIUS_ENABLED}"
wait "$OPENVPN_PID"
